version: 0.2
env:
  shell: bash
phases:
  pre_build: # commands to be run before build
    commands:
      - echo Logging in to Amazon ECR....
      - aws --version
      # login to Elastic container registry
      - docker login -u AWS -p $(aws ecr get-login-password --region eu-west-1) 607961807593.dkr.ecr.eu-west-1.amazonaws.com
      - REPOSITORY_URI=607961807593.dkr.ecr.eu-west-1.amazonaws.com/php-test
      - IMAGE_TAG=latest
  build:
    commands:
      - echo Build started on `date`
      - echo installing composer..
      - composer install
      - echo creating .env file..
      - cp .env.example .env
      - echo generating app key
      - php artisan key:generate
      - echo Building the Docker image...
      - docker build -t php-test .
      - docker tag php-test:latest 607961807593.dkr.ecr.eu-west-1.amazonaws.com/php-test:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker image ls -a
      - docker push 607961807593.dkr.ecr.eu-west-1.amazonaws.com/php-test:latest
